FORMAT: 1A

# dacuda3d
API to calculate mesh data on the server. Will run on manis.dacuda.com. Google App Engine will send data3d TAR via POST request, and get back the calculated mesh (obj).

# Group image
Image to Mesh API

## Notes Collection [/images]
### Calculate a Mesh [POST]
+ Request (application/json)

        {
            "tar": "base64 encoded tar file"
        }

+ Response 200 (application/json)

        {
            "jpg" : "base64 encoded jpeg",
            "mvp" : ["0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000"],
            "cam" : ["0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000"],
            "sph" : ["0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000", "0.000"],
            "obj": "# Blender v2.54 (sub 0) OBJ File: in plaintext"
        }
