FORMAT: 1A

# dacuda3d
API to calculate mesh data on the server. Will run on manis.dacuda.com. Google App Engine will send data3d TAR via POST request, and get back the calculated mesh (obj).

# Group image
Image to Mesh API

## Mesh Calculation on Meshing Server [/]
### Calculate a Mesh [POST]
+ Request (application/json)

        {
            "tar": "base64 encoded tar file",
            "callback": "https://dacuda3d.appspot.com/captures/<key>/mesh"
        }

+ Response 200 (application/json)
        
        {
            "status": "ok"
        }

# Group callback to GAE

## Callback to GAE [/captures/key/mesh]
### Callback from Meshing server with result [POST]
AppEngine stores:
* latest obj as capture.obj3d
* quality under capture.quality[version] = ... (so that all quality measurements from old versions remain stored)
* latest images2d, list of 2D images in data.json, and images themselves underneath /captures/<key>/data2/...?scale=X
* latest arc angles, accessible in data.json

+ Request (application/json)

        {
            "version": "0.2.6.234_76acda41f",
            "obj": "# Blender v2.54 (sub 0) OBJ File: in plaintext",
            "quality": {
                "visible": "28.9886",
                "diff": "83.0343"
            },
            "images2d": [
                {
                    "img": "base64 encoded png 1",
                    "angle": 110.0123
                },
                {
                    "img": "base64 encoded png 2",
                    "angle": 160.0123
                },
                {
                    "img": "base64 encoded png 3",
                    "angle": 190.0123
                },
            "arc": {
                "min_angle": -30,
                "max_angle": 190.0123
            }
        }

+ Response 200 (application/json)

        {
            "status": "ok"
        }

# Group API to Web Viewer
## Request info about dataset [/captures/key/data.json]
### GET
+ Response 200 (application/json)

        {
          "images": [
            "0000.jpg", 
            "0001.jpg", 
            "0003.jpg", 
            "0004.jpg", 
            "0005.jpg", 
            "0006.jpg", 
            "0007.jpg", 
            "0008.jpg", 
            "0009.jpg", 
            "0010.jpg", 
            "0011.jpg"
          ],
          "original_size": {
            "width": 1080,
            "height": 1440
          },
          "images2d": [
            {"name": "0_groundtruth.png", "angle": 0.249391},
            {"name": "1_groundtruth.png", "angle": 15.7231},
            {"name": "2_groundtruth.png", "angle": 45.8254},
            {"name": "3_groundtruth.png", "angle": 78.7173},
            {"name": "4_groundtruth.png", "angle": 107.363},
            {"name": "5_groundtruth.png", "angle": 135.763},
            {"name": "6_groundtruth.png", "angle": 166.009},
            {"name": "7_groundtruth.png", "angle": -157.619},
            {"name": "8_groundtruth.png", "angle": -131.708},
            {"name": "9_groundtruth.png", "angle": -100.915},
            {"name": "10_groundtruth.png", "angle": -73.2636},
            {"name": "11_groundtruth.png", "angle": -42.7094}
          ],
          "original_size_2d": {
            "width": 1026,
            "height": 1026
          },
          "arc": {
            "min_angle": -180,
            "max_angle": 180
          }
        }


